# Generated by Django 3.2.5 on 2022-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='data',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
