# Generated by Django 3.2.5 on 2022-07-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackAPI', '0002_auto_20220704_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.RemoveField(
            model_name='data',
            name='tags',
        ),
    ]
