# Generated by Django 3.2.5 on 2022-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackAPI', '0003_auto_20220704_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=models.TextField(blank=True),
        ),
    ]
