# Generated by Django 3.2.5 on 2022-07-05 07:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StackAPI', '0004_alter_data_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=jsonfield.fields.JSONField(),
        ),
    ]
