# Generated by Django 3.2.5 on 2022-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackAPI', '0005_alter_data_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=models.JSONField(),
        ),
    ]
